  
version: 2.1
orbs:
  node: circleci/node@4.0.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.3
      - image: circleci/mongo:4.4.1-ram
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm db-seed